### ISSUE TITLE
Exclusion List

### ISSUE THREAD

**Issue by SovnSkyrim** [tr4wzified/AOSISCSoundPatcher#1]
Excluding certain esps would be nice to avoid cloaks or scarfs to have amulet sounds.

**Comment by tr4wzified** [comment]
Hmm, interesting. I wonder if those should even have the keyword in the first place, that seems kinda odd.

**Comment by tr4wzified** [comment]
Do you need those keywords for anything else? I'd consider patching those out first

**Comment by tr4wzified** [comment]
Not within the scope of the patcher, would be more of a Synthesis feature
