### ISSUE TITLE
Too many masters in big modlists - potential simple solution

### ISSUE THREAD

**Issue by Sirgilly** [tr4wzified/AOSISCSoundPatcher#10]
357014Hi,

I am finding I cant use the patcher as there are too many masters. I noticed Item weight customizer allows you to get around this by having items be selectable. This actually allows you to run the patcher twice, once for books and notes perhaps and then again for other misc items. Perhaps a couple of setting here to run for weapons and spells separately?

Sirgilly

**Comment by tr4wzified** [comment]
I do want to look into this to make it so that you can select what elements to patch, that should help a little at least.

**Comment by tr4wzified** [comment]
Added some settings to select what to patch.
