### ISSUE TITLE
Error too many master files on big load orders

### ISSUE THREAD

**Issue by XarisZ** [tr4wzified/AOSISCSoundPatcher#11]
You cannot use this patch on big loadorders

**Comment by Noggog** [comment]
This is not a problem of this patcher, specifically, but more the current limitations of the entire system
https://github.com/Mutagen-Modding/Synthesis/discussions/300

**Comment by MinhazMurks** [comment]
Maybe there can be settings to allow only armor sounds etc. should be added?

**Comment by tr4wzified** [comment]
Closing this and leaving #10 open as it's the same issue. Do want to do something about this to help a little at least, not sure when I'll get to it
