### ISSUE TITLE
Did you mean to increase it to .net 7?

### ISSUE THREAD

**Issue by Michael-wigontherun** [tr4wzified/AOSISCSoundPatcher#13]
```<TargetFramework>net7.0</TargetFramework>```

**Comment by tr4wzified** [comment]
Yes. You can download the .NET 7 SDK here: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.200-windows-x64-installer 
If it doesn't work right away after installing it, you may have to reboot first.
