### ISSUE TITLE
Hardcoded Forms cause errors when AOS or ISC are compacted or merged.

### ISSUE THREAD

**Issue by Fuzzlesz** [tr4wzified/AOSISCSoundPatcher#2]
The hardcoded forms cause resolve errors when used on a load order containing compacted or merged versions of the mods.

**Comment by tr4wzified** [comment]
Personally, I'd recommend against compacting/merging AOS or ISC because there are still a ton of patches you'll likely need that'll stop working if the base plugin has changed. Or are you merging those together with AOS & ISC? I suppose I could fall back to some kind of resolve method by EditorID.

**Comment by Fuzzlesz** [comment]
Unfortunately when working with the quantity of mods I am some things need to be done that it would be easier to not do lol


I've compacted mine, but I have my final modlist in hand so all my patches were loaded and sorted out by xedit. I know what I'm looking for, but I'd be concerned if in the future someone ran your patch with a stack of others, didn't look at output, then things get crashy lol

**Comment by tr4wzified** [comment]
Since EDIDs are not unique I don't think there's any way to reliably determine which form originally belongs to the mod. Plus this is a super niche use case, I would recommend merging/compacting other mods instead.
