### ISSUE TITLE
Spell Integration Suggestion

### ISSUE THREAD

**Issue by DerrylHopkins** [tr4wzified/AOSISCSoundPatcher#3]
Hey Trawz,

Would it be possible for this patcher to support mod-added spells in the future so that mod such as [Mysticism - A Magic Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/27839) can receive the sounds from AOS/ISC to its new spells?

Thanks,
Aosana

P.S. I do not know why I structured this issue like an email.

**Comment by tr4wzified** [comment]
Working on it

**Comment by tr4wzified** [comment]
Available now on the experimental branch. Will do some more testing / maybe add some additional features, but should work :)
