### ISSUE TITLE
Name missing from many basic items

### ISSUE THREAD

**Issue by Spamerton** [tr4wzified/AOSISCSoundPatcher#7]
This is a great attempt at fixing Audio Overhaul and ISC.

However, I did the quest for Amren's Family Sword and noticed it did not show up in the chest it was supposed to be in.  After looking in xEdit, I noticed that the name was missing from the record (see screenshot).  After adding the name, the items showed up in the chest.  After spending several hours troubleshooting, I isolated your synthesis script and ran it alone.  Indeed it was not only that item, but several others that are missing their names.  This is most certainly a bug:

![image](https://user-images.githubusercontent.com/95182542/143778056-69af61a1-8cd3-45d4-82c0-03b44b57a4bd.png)

I attempted with both the "Latest" and the "Match" versions:

![image](https://user-images.githubusercontent.com/95182542/143778235-6bd8b91b-6e0d-43c8-8fb1-ccd5915afac2.png)

**Comment by tr4wzified** [comment]
That is incredibly strange since this patcher should not even affect names. Are you sure that you didn't have a mod loaded that removed the name, ran the patcher and forgot to rerun it? I'll contact Noggog (maintainer of Synthesis/Mutagen), maybe he has an idea.

**Comment by Spamerton** [comment]
I apologize, and thank you for looking into it.  I was going to demonstrate that it worked w/o your patcher, but that's not true.  Those names still didn't show up.  You can close this, it's obviously something with my load order.

**Comment by tr4wzified** [comment]
Alright, I hope you'll find the cause soon :)
