### ISSUE TITLE
Patches items with templates

### ISSUE THREAD

**Issue by zhongjiedong** [tr4wzified/AOSISCSoundPatcher#9]
Patcher will touch records with templates for example enchanted items. This is generating thousands of unnecessary records.

This is how they fixed it for the speed and reach fixes patcher: https://github.com/Synthesis-Collective/speedandreachfixes/commit/5fb406c983d3b70b2723047d1c856e83a43315ae

**Comment by tr4wzified** [comment]
Fixed.
